runtime: php73
runtime_config: 
  document_root: rmuti-coop-inventory.et.r.appspot.com
handlers:
  - url: /css
    static_dir: css
env_variables:
  MYSQL_HOST: mysql:urlx_socket=/cloudsql/rmuti-coop-inventory:asia-southeast1:mysql-rmuti-coop
  MYSQL_DB: inventory
  MYSQL_USER: root
  MYSQL_PASS: b044655658
  